[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "EStore"
version = "0.1.0"
description = "ECommerce Store project"
authors = [{ name = "Sandeep Surnella" }]
dependencies = []
