[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "EStore"
version = "0.1.0"
description = "ECommerce Store project"
authors = [{ name = "Sandeep Surnella" }]
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

